[tool.poetry]
name = "Jandig"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
MarkupSafe = "^2.1.1"
Django = "^4.0.6"
Jinja2 = "^3.1.2"
gunicorn = "^20.1.0"
Pillow = "^9.2.0"
django-cors-headers = "^3.13.0"
invoke = "^1.7.1"
django-environ = "^0.9.0"
psycopg2-binary = "^2.9.3"
django-boogie = "^0.13.3"
Sphinx = "^5.0.2"
Babel = "^2.10.3"
django-debug-toolbar = "^3.5.0"
gevent = "^21.12.0"
pymarker = "^0.3.1"
django-extensions = "^3.1.5"
factory-boy = "^3.2.1"
boto3 = "^1.24.27"
django-storages = "^1.12.3"
sentry-sdk = "^1.7.0"
whitenoise = "^6.2.0"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
