name: Requirements pipeline

on:
  push:
    paths:
      - 'pyproject.toml'

jobs:
  dependencies:
    name: test / dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Check poetry lock
        run: |
          poetry update --lock
